name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  #job 1
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.0"
          cache: true

      - name: Install dependencies
        run: |
          go mod download
      
      - name: Build
        run: go build -o server ./cmd/app.go

  #job 2
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ secrets.USERNAME }}/apprenticeship-project:ci-${{ github.sha }} .

      - name: Save image
        run: docker save ${{ secrets.USERNAME }}/apprenticeship-project:ci-${{ github.sha }} | gzip > image.tar.gz
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: image.tar.gz

  #job 3
  liatrio-apprentice-actions:
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
      
      - name: Load image
        run: docker load < image.tar.gz

      - name: Run container
        run: docker run -d -p 80:80 ${{ secrets.USERNAME }}/apprenticeship-project:ci-${{ github.sha }}

      - name: Wait for app to be ready
        run: sleep 5

      - name: run tests
        #uses: liatrio/github-actions/apprentice-action@master
        uses: liatrio/github-actions/apprentice-action@8d1edd61c1967483150893d301ca6334e7f0673c

  #job 4
  push-to-Docker-Hub:
    runs-on: ubuntu-latest
    needs: liatrio-apprentice-actions
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: load image
        run: docker load < image.tar.gz

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      
      - name: Push to Docker Hub
        run: docker push ${{ secrets.USERNAME }}/apprenticeship-project:ci-${{ github.sha }}